name: Publish docs

on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version number
        required: true

jobs:

  # Generate docs on GitHub pages
  docs:
    name: 'Generate docs'
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@main

      # Update version number
      - name: Update version number
        uses: jacobtomlinson/gha-find-replace@2.0.0
        with:
          find: "VERSIONADDEDBYGITHUB"
          replace: "${{ github.event.inputs.version || github.ref_name }}"
          regex: false

      # Minimal package setup
      - name: Install dependencies
        run: dart pub get # Don't use `make pull_deps`, will override version number
        working-directory: ${{ inputs.working-directory }}

      # Generate docs
      - name: Generate docs
        run: dart doc # Don't use `make docs`, will override version number

      # Deploy docs to GitHub pages
      - name: Deploy docs to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/api
